# Behavioral Control Configuration
rules:
  max_attempts: 3
  allow_mock_data: false
  allow_workarounds: false
  require_help_after_failures: true

file_locations:
  test_outputs: project_state/artifacts/
  validation_scripts: scripts/
  help_requests: project_state/
  logs: project_state/artifacts/

forbidden_patterns:
  - test_*.py in root
  - *_baseline*.py in root
  - run_*day*.py in root
  - duplicate validators